---
title: "Ejercicios: R como lenguaje de programación"
output:
  pdf_document: default
  html_notebook: default
---
# Ejercicio 1:

Dados los vectores v1=c(1,2,3,4,5) y v2=c(4,5,8,9) comparar cada elemento del vector v1 con cada elemento del vector v2 y seleccionar los elementos de v1 menores a todos los elementos de v2. 

Usar las sentencias "for" "if" y el operador lógico all( a < b).

Imprimir los números seleccionados en pantalla.


# Ejercicio 2:

Leer los nombres de los archivos .csv de este directorio y alojarlos como elementos de una lista (usar el comando "list.files"). Recordar que podemos mirar el help haciendo ?list.files.

Leer el primer archivo de la lista y examinar el número de filas (usar "read.table", leer también el título de las columnas del archivo con la opción "header" y tener en cuenta que los datos están separados por espacios). Recordar que podemos mirar el help haciendo ?read.table.

Suponiendo que todos los archivos tienen el mismo número de filas, leer con un loop cada uno de los elementos de la lista de archivos y armar una sola matriz con las columnas no repetidas.
Para esto tener en cuenta que la expresión !(a %in% b) sirve para preguntar si el elemento a no está incluído en el vector b.

En la matriz resultado conservar los nombres de los headers originales.


# Ejercicio 3:
Calcular con un loop, el promedio de cada columna de la matriz del ejercicio anterior y alojar los promedios en un vector. Imprimir el resultado en pantalla.


# Ejercicio 4:
Dado un conjunto de números alojados en un vector, construir una función que me calcule la media y la desviación estandard. 

Recordar que la media aritmética se calcula como:

$\mu= (x_1+x_2+x_3+....+x_n)/n$

Y la desviación estandard se calcula como:

$\sigma= \sqrt {\frac{1}{n} \sum_i{(x_i-\mu)^2}}$

Calcular ambas medidas estadísticas para cada uno de los siguientes vectores contenidos en la lista[[i]]:

```{r}
lista<-list()
for(i in 1:150){
lista[[i]]<-rnorm(100,mean=i,sd=5)
}
```
Expresar los resultados como dos vectores: vector_media y vector_desviación estandard. Imprimirlos por pantalla.

# Ejercicio 5:
Cargar el archivo "datosvelocidadgliroides.csv" de éste directorio. La primer columna corresponde a datos medidos de velocidades de un micromamífero en el bosque, la segunda columna es la correspondiente frecuencia con que se miden esas velocidades (Es decir que el archivo contiene un histograma de velocidades). Graficar en el eje x las velocidades y en el eje y la frecuencia y ajustar con una distribución lognormal construyendo la función y usando nls() para hacer el ajuste no lineal de la función. 
Recordar que la lognormal puede escribirse como:

$lognormal(x)=\frac{1}{\sigma x \sqrt{2\pi}} exp(- \frac{(log(x)-\mu)^2}{2\sigma^2})$

donde $\sigma$ y $\mu$ serán los parámetros de la función.

la media de la distribución es:

$media= exp(\mu+\frac{\sigma^2}{2})$

$mediana=exp(\mu)$

$varianza=exp(2\mu+\sigma^2)(exp(\sigma^2)-1)$

Para el ajuste utilizar los siguientes valores iniciales:

nls(y ~ funcionconstruida, start = list(mu=log(1.9), sigma=log(2.5)),algorithm = "plinear")


Graficar el histograma del archivo y la línea del ajuste en color rojo.